"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Download, X, Sparkles } from "lucide-react";

export default function ResourceModal({
  selectedResource,
  setSelectedResource,
  getFileType,
}: any) {
  if (!selectedResource) return null;

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={() => setSelectedResource(null)}
      >
        <motion.div
          className="w-full max-w-7xl bg-gradient-to-br from-[#0f172a]/90 to-[#020617]/90 border border-white/10 rounded-3xl p-6 backdrop-blur-xl shadow-[0_0_60px_rgba(0,0,0,0.8)]"
          onClick={(e) => e.stopPropagation()}
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
          transition={{ duration: 0.25 }}
        >
          {/* Header */}
          <div className="flex justify-between items-start mb-4">
            <div>
              <h2 className="text-xl font-bold text-white">
                {selectedResource.title}
              </h2>

              {selectedResource.description && (
                <p className="text-gray-400 text-sm mt-1">
                  {selectedResource.description}
                </p>
              )}
            </div>

            <div className="flex items-center gap-2">
              <a
                href={selectedResource.url}
                target="_blank"
                rel="noopener noreferrer"
                download
                className="p-2 bg-white/10 rounded-full hover:bg-cyan-500/20 transition"
                title="Download"
              >
                <Download size={18} className="text-gray-300" />
              </a>

              <button
                onClick={() => setSelectedResource(null)}
                className="p-2 bg-white/10 rounded-full hover:bg-white/20 transition"
              >
                <X size={18} className="text-gray-300" />
              </button>
            </div>
          </div>

          {/* Body */}
          <div className="flex gap-4 h-[70vh]">
            {/* LEFT: Preview */}
            <div className="flex-1 rounded-xl overflow-hidden border border-white/10 bg-black/40">
              {getFileType(selectedResource.url) === "pdf" && (
                <iframe
                  src={`https://docs.google.com/gview?url=${encodeURIComponent(
                    selectedResource.url,
                  )}&embedded=true`}
                  className="w-full h-full"
                />
              )}

              {getFileType(selectedResource.url) === "image" && (
                <img
                  src={selectedResource.url}
                  alt={selectedResource.title}
                  className="w-full h-full object-contain"
                />
              )}

              {getFileType(selectedResource.url) === "video" && (
                <video
                  src={selectedResource.url}
                  controls
                  className="w-full h-full"
                />
              )}

              {getFileType(selectedResource.url) === "audio" && (
                <div className="flex items-center justify-center h-full">
                  <audio controls src={selectedResource.url} />
                </div>
              )}

              {getFileType(selectedResource.url) === "other" && (
                <div className="flex items-center justify-center h-full text-gray-400">
                  Preview not available
                </div>
              )}
            </div>

            {/* RIGHT: AI Summary */}
            {selectedResource.aiSummary?.length > 0 && (
              <div className="w-80 flex flex-col gap-3 overflow-y-auto">
                {/* Header */}
                <div className="bg-violet-500/10 border border-violet-500/20 rounded-2xl p-4">
                  <h3 className="text-violet-400 font-bold flex items-center gap-2 mb-1">
                    <Sparkles size={16} /> AI Summary
                  </h3>
                  <p className="text-gray-500 text-xs">
                    Generated by AI from document content
                  </p>
                </div>

                {/* Points */}
                <div className="flex flex-col gap-3">
                  {selectedResource.aiSummary.map(
                    (point: string, i: number) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.08 }}
                        className="bg-white/5 border border-white/10 rounded-xl p-4 hover:border-violet-500/30 hover:bg-violet-500/5 transition-all"
                      >
                        <div className="flex gap-3 items-start">
                          <span className="text-violet-400 font-bold text-sm mt-0.5 shrink-0">
                            {String(i + 1).padStart(2, "0")}
                          </span>
                          <p className="text-gray-300 text-sm leading-relaxed">
                            {point}
                          </p>
                        </div>
                      </motion.div>
                    ),
                  )}
                </div>

                {/* PDF fallback */}
                {getFileType(selectedResource.url) === "pdf" && (
                  <p className="text-gray-500 text-xs text-center mt-auto pt-2">
                    PDF not loading?{" "}
                    <a
                      href={selectedResource.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-cyan-400 hover:underline"
                    >
                      Open in new tab
                    </a>
                  </p>
                )}
              </div>
            )}
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
