import { prisma } from "@/lib/prisma";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextRequest, NextResponse } from "next/server";
import z from "zod";
const pdfParse = require("pdf-parse");

const genAi = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");
const model = genAi.getGenerativeModel({
  model: "gemini-2.5-flash",
  generationConfig: { responseMimeType: "application/json" },
});
const analyzeSchema = z.object({
  submissionId: z.string().cuid(),
  teacherId: z.string().cuid(),
});
async function fetchPDFAsBase64(url: string): Promise<string> {
  try {
    const response = await fetch(url, { cache: "no-store" });
    if (!response.ok) {
      throw new Error("Failed to fetch PDF");
    }
    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    return buffer.toString("base64");
  } catch (error) {
    console.error("PDF parsing error:", error);
    return "";
  }
}
function safeJSONParse(text: string) {
  try {
    return JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);
    if (match) {
      return JSON.parse(match[0]);
    }
    throw new Error("Invalid JSON from AI");
  }
}
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validation = analyzeSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json({ error: "Invalid input" }, { status: 400 });
    }
    const { submissionId, teacherId } = validation.data;
    const submission = await prisma.submission.findUnique({
      where: { id: submissionId },
      include: { assignment: true },
    });
    if (!submission) {
      return NextResponse.json(
        { error: "Submission not found" },
        { status: 404 },
      );
    }
    const teacherProfile = await prisma.teacher.findFirst({
      where: { userId: teacherId, id: submission.assignment.teacherId },
    });
    if (!teacherProfile) {
      return NextResponse.json(
        { error: "Unauthorized access" },
        { status: 403 },
      );
    }
    if (submission.aiSummary?.length > 0 && submission.aiProbability !== null) {
      return NextResponse.json({
        success: true,
        summary: submission.aiSummary,
        aiProbability: submission.aiProbability,
        cached: true,
      });
    }
    let textContent = submission.text ?  `Written Answer from student: \n${submission.text}\n\n`:"";
    let pdfBase64 = "";

    if (submission.fileUrl?.endsWith(".pdf")) {
      pdfBase64 = await fetchPDFAsBase64(submission.fileUrl);
    }
    if (!textContent && !pdfBase64) {
      return NextResponse.json(
        { error: "No content available for analysis." },
        { status: 422 },
      );
    }
    const prompt = `
      Analyze the following student submission carefully.
      Provide exactly three concise bullet points summarizing the key findings.
      Also estimate the probability that this work was generated by AI (0-100).
      Return STRICT JSON: { "summary": ["point 1", "point 2", "point 3"], "aiProbability": 85 }
      
      ${textContent}
    `;
     const aiParts: any[] = [prompt];

     if (pdfBase64) {
      aiParts.push({
        inlineData:{
          data: pdfBase64,
          mimeType:"application/pdf",
        }
      })
     }
    const result = await model.generateContent(aiParts);
    const aiText = result.response.text();
    const jsonResponse = safeJSONParse(aiText);
    if (
      !jsonResponse?.summary ||
      typeof jsonResponse.aiProbability !== "number"
    ) {
      throw new Error("Invalid AI response format");
    }
    await prisma.submission.update({
      where: { id: submissionId },
      data: {
        aiSummary: jsonResponse.summary,
        aiProbability: jsonResponse.aiProbability,
      },
    });
    return NextResponse.json({
      success: true,
      summary: jsonResponse.summary,
      aiProbability: jsonResponse.aiProbability,
      cached: false,
    });
  } catch (error) {
    console.error("AI analysis error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 },
    );
  }
}
